<?php
/**
 * Created by PhpStorm.
 * User: Gabriel
 * Date: 19/10/2018
 * Time: 12:31 PM
 */

namespace tests\service_order;


use daos\CoreDAO;

class ServiceOrderDAO extends CoreDAO
{
    public function getPaginationConfiguration(): array
    {
        $config = parent::getPaginationConfiguration();
        $config["defaultLimit"] = 20;
        return $config; // TODO: Change the autogenerated stub
    }


}